### ISSUE TITLE
username is used as group name

### ISSUE THREAD

**Issue by domano** [gantsign/ansible-role-visual-studio-code#101]
Hi,

i wanted to use your role, but ran into an issue with custom configurations.

`TASK [ansible-role-visual-studio-code : create config directories for users] **************************************************************************************************************************************
failed: [localhost] (item=({u'username': u'domano', u'visual_studio_code_settings': {u'files.autoSave': u'afterDelay', u'files.autoSaveDelay': 1000, u'git.autofetch': True, u'explorer.openEditors.visible': 0}}, u'Ansible')) => {"changed": false, "gid": (removed groupid here), "group": "somegroup", "item": [{"username": "domano", "visual_studio_code_settings": {"explorer.openEditors.visible": 0, "files.autoSave": "afterDelay", "files.autoSaveDelay": 1000, "git.autofetch": true}}, "Ansible"], "mode": "0711", "msg": "chgrp failed: failed to look up group domano", "owner": "domano", "path": "/home/domano/.config", "size": 4096, "state": "directory", "uid": (removed my user id here)}
`

My playbook looks like this (at least the relevant part):
`      visual_studio_code_version: '1.21' 
      users:
        - username: domano
          visual_studio_code_extensions:
            - Ansible
            - ansible-autocomplete
            - Go
            - IntelliJ IDEA Keybindings
            - language-Ansible
          visual_studio_code_settings: {  
              "explorer.openEditors.visible": 0,
              "git.autofetch": true,
              "files.autoSave": "afterDelay",
              "files.autoSaveDelay": 1000
          }`

**Comment by freemanjp** [comment]
@domano, sorry for not getting this earlier, you should find the issue you reported is fixed in version [3.0.0](https://github.com/gantsign/ansible-role-visual-studio-code/releases/tag/3.0.0) of this role.
