### ISSUE TITLE
Duplicate sources.list entry for vs-code

### ISSUE THREAD

**Issue by eraserix** [gantsign/ansible-role-visual-studio-code#113]
On Debian, this role leads to duplicate entries for the microsoft apt repository:

- One is created by the role to install visual studio code (package_microsoft_com_repos_vscode.list)
- The other entry is created by the Debian package of visual studio code (vscode.list)

This creates warnings about duplicate entries:
```
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/packages_microsoft_com_repos_vscode.list:1 and /etc/apt/sources.list.d/vscode.list:3
```
I suggest removing the entry that is created by the role and relying on the one that is created by vs-code during installation.

**Comment by freemanjp** [comment]
@eraserix thanks for reporting this issue. You should find the issue is resolved in the [4.0.1](https://github.com/gantsign/ansible-role-visual-studio-code/releases/tag/4.0.1) release of this role.
