### ISSUE TITLE
Interactive vscode windows opening when installing extensions

### ISSUE THREAD

**Issue by conclavia** [gantsign/ansible-role-visual-studio-code#144]
Let me start by saying this role is completely awesome and has saved me a lot of pain! :-)

When running the role with extensions that are already installed I'm getting a lot of interactive vscode windows opening up. I've been able to reproduce the problem manually, and it looks like it has to do with the order of the parameters provided to vscode.

I think the issue is in the `install_extension` function in `visual_studio_code_install_extension.py`.

`        rc, out, err = module.run_command(
            ['code', '--install-extension', '--force', name])`

Should be:

`        rc, out, err = module.run_command(
            ['code', '--install-extension', name, '--force'])`

Currently running with:
- ubuntu 18.04.1
- ansible 2.5.1
- vscode v1.30.0
- gantsign.visual-studio-code v6.2.0

**Comment by freemanjp** [comment]
@conclavia thanks for reporting this issue and your time investigating to determine the solution. I'm sorry it's taken me so long to commit the fix. You can find the fix in the [6.2.1](https://github.com/gantsign/ansible-role-visual-studio-code/releases/tag/6.2.1) release of this role.
