### ISSUE TITLE
Is CXXABI_1.3.9 requirement new?

### ISSUE THREAD

**Issue by guleyupo** [gantsign/ansible-role-visual-studio-code#187]
I am getting an error when trying to install extensions on a RedHat 7.9 Workstation system:

"msg": "Error querying installed extensions [vscjava.vscode-java-pack]: **Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found** (required by /usr/share/code/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)\n    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)\n    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)\n    at Module.load (internal/modules/cjs/loader.js:1039:32)\n    at Module._load (internal/modules/cjs/loader.js:932:14)\n    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)\n    at Module.require (internal/modules/cjs/loader.js:1079:19)\n    at require (internal/modules/cjs/helpers.js:72:18)\n    at bindings (/usr/share/code/resources/app/node_modules.asar/bindings/bindings.js:112:48)\n    at Object.<anonymous> (/usr/share/code/resources/app/node_modules.asar/spdlog/index.js:3:35)\n    at Module._compile (internal/modules/cjs/loader.js:1199:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)\n    at Module.load (internal/modules/cjs/loader.js:1039:32)\n    at Module._load (internal/modules/cjs/loader.js:932:14)\n    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)\n    at Module.require (internal/modules/cjs/loader.js:1079:19)\n    at require (internal/modules/cjs/helpers.js:72:18)\n    at t (/usr/share/code/resources/app/out/vs/loader.js:4:101)\n    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:13249)\n    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)\n    at c (/usr/share/code/resources/app/out/vs/loader.js:4:10314)\n    at Object.errorback (/usr/share/code/resources/app/out/vs/loader.js:4:10435)\n    at r.triggerErrorback (/usr/share/code/resources/app/out/vs/loader.js:3:10626)\n    at /usr/share/code/resources/app/out/vs/loader.js:3:10332\n    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:13266)\n    at r.load (/usr/share/code/resources/app/out/vs/loader.js:3:10262)\n    at c (/usr/share/code/resources/app/out/vs/loader.js:4:10314)\n    at r._loadModule (/usr/share/code/resources/app/out/vs/loader.js:4:10444)\n    at r._resolve (/usr/share/code/resources/app/out/vs/loader.js:5:452)\n    at r.defineModule (/usr/share/code/resources/app/out/vs/loader.js:4:6145)\n    at r._relativeRequire (/usr/share/code/resources/app/out/vs/loader.js:4:6831)\n    at n (/usr/share/code/resources/app/out/vs/loader.js:4:9420)\n    at f (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:13:42562)\n    at new Promise (<anonymous>)\n    at b (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:13:42542)\n    at m._createSpdLogLogger (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:13:43517)\n    at new m (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:13:43322)\n    at c.initServices (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:16:57027)\n    at async c.run (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:16:56421)\n    at async Object.h [as main] (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:16:59927)\n    at async C (/usr/share/code/resources/app/out/vs/code/node/cli.js:12:13346) {\n  phase: 'loading',\n  moduleId: 'spdlog',\n  neededBy: [ '===anonymous5===' ]\n}\n"
}

When I query the library, it does not have the required version as the error says:

```
$ nm -D /lib64/libstdc++.so.6 | grep CXXABI
0000000000000000 A CXXABI_1.3
0000000000000000 A CXXABI_1.3.1
0000000000000000 A CXXABI_1.3.2
0000000000000000 A CXXABI_1.3.3
0000000000000000 A CXXABI_1.3.4
0000000000000000 A CXXABI_1.3.5
0000000000000000 A CXXABI_1.3.6
0000000000000000 A CXXABI_1.3.7
0000000000000000 A CXXABI_TM_1
```

I am pretty sure this worked before though. Any idea what may be wrong?

**Comment by freemanjp** [comment]
@guleyupo, since VS Code 1.53 you'll need a minimum of RedHat EL 8 / CentOS 8. See https://code.visualstudio.com/updates/v1_53#_electron-11-update. I need to update the documentation for this role.

**Comment by guleyupo** [comment]
I see. Thanks for the quick reply and this useful role!

    On Monday, February 8, 2021, 02:05:07 AM EST, John Freeman <notifications@github.com> wrote:  
 
 


@guleyupo, since VS Code 1.53 you'll need a minimum of RedHat EL 8 / CentOS 8. See https://code.visualstudio.com/updates/v1_53#_electron-11-update. I need to update the documentation for this role.

**Comment by guleyupo** [comment]
I should note though (for anyone who ends up here) even though the automated installtion of extension fails with VS Code 1.53, this role does still work and installs VS Code itself. One just has to manually install the extensions through the VS Code GUI. That still works.
