### ISSUE TITLE
Provide facility to install only VS Code extensions 

### ISSUE THREAD

**Issue by NileshGule** [gantsign/ansible-role-visual-studio-code#79]
I use Home-brew Cask to install VS Code on my Mac. I would like to request a feature where you can install VS code beforehand and use the role just of installing the plugins.
The role can be customized for MacOS only as Home-brew cask is built for Mac.

**Comment by freemanjp** [comment]
@NileshGule as you appear to have spotted, I've written a separate plugin for just installing plugins (https://github.com/gantsign/ansible-role-visual-studio-code-extensions), though it hasn't been tested on MacOS.
